//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSMSClient.ServiceReference4 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/Book_Store_Management_System")]
    [System.SerializableAttribute()]
    public partial class Payment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int order_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string payment_MethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string payment_StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((this.order_idField.Equals(value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payment_Method {
            get {
                return this.payment_MethodField;
            }
            set {
                if ((object.ReferenceEquals(this.payment_MethodField, value) != true)) {
                    this.payment_MethodField = value;
                    this.RaisePropertyChanged("payment_Method");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payment_Status {
            get {
                return this.payment_StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.payment_StatusField, value) != true)) {
                    this.payment_StatusField = value;
                    this.RaisePropertyChanged("payment_Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.IService4")]
    public interface IService4 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/PaymentInsert", ReplyAction="http://tempuri.org/IService4/PaymentInsertResponse")]
        bool PaymentInsert(BSMSClient.ServiceReference4.Payment payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/PaymentInsert", ReplyAction="http://tempuri.org/IService4/PaymentInsertResponse")]
        System.Threading.Tasks.Task<bool> PaymentInsertAsync(BSMSClient.ServiceReference4.Payment payment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService4Channel : BSMSClient.ServiceReference4.IService4, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service4Client : System.ServiceModel.ClientBase<BSMSClient.ServiceReference4.IService4>, BSMSClient.ServiceReference4.IService4 {
        
        public Service4Client() {
        }
        
        public Service4Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service4Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service4Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service4Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool PaymentInsert(BSMSClient.ServiceReference4.Payment payment) {
            return base.Channel.PaymentInsert(payment);
        }
        
        public System.Threading.Tasks.Task<bool> PaymentInsertAsync(BSMSClient.ServiceReference4.Payment payment) {
            return base.Channel.PaymentInsertAsync(payment);
        }
    }
}
